name: riverpod_rewards
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+11

environment:
   sdk: ^3.8.0  

dependencies:
  flutter:
    sdk: flutter
  #state management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  #hooks
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.0

  #localization
  flutter_localizations:
    sdk: flutter

  #app icon
  cupertino_icons: ^1.0.4

  #image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.2.1

  #pull to refresh
  pull_to_refresh: ^2.0.0

  #firebase
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0

  #webview
  webview_flutter: ^4.2.0

  #package info
  package_info_plus: ^9.0.0

  #network connectivity
  connectivity_plus: ^7.0.0

  #environment variables
  envied: ^1.2.1

  #navigation
  go_router: ^17.0.0

  dartz: ^0.10.1
  #dependency injection
  injectable: ^2.5.1
  get_it: ^9.0.5

  #UI
  adaptive_theme: ^3.4.0
  fluttertoast: ^9.0.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  url_launcher: ^6.1.14
  extended_image: ^10.0.1
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0

  gradient_borders: ^1.0.0
  percent_indicator: ^4.2.3
  flutter_widget_from_html: ^0.17.1


  #network
  dio: ^5.3.2
  
  #Local storage
  shared_preferences: ^2.2.1

  #serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.5
  


flutter_icons:
  android: "ic_launcher"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
#    generate: true
#    image_path: "assets/app_icon2.png"
#    background_color: "#021D49"
#    theme_color: "#021D49"
  # then run
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main
  # then you can delete package and photo and these code

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: ^2.8.11
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.0

  build_runner: ^2.7.1
  freezed: ^3.2.0

  #envied generator
  envied_generator: ^1.2.1
  
  #injectable generator
  injectable_generator: ^2.6.2

  #riverpod generator
  riverpod_generator: ^3.0.0

  #riverpod lint
  riverpod_lint: ^3.0.0


  #test
  mockito: ^5.5.0
  # bloc_test: ^10.0.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/avatars/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic


flutter_intl:
  enabled: true
